openapi: '3.0.0'
info:
 description: this is test 
 title: Alex..
 version: 1.0.0
paths: 
  /user:
    get:
      parameters:
        - name: id
          in: query
          schema: 
            type: string
      operationId: testing
      summary: get user by ID
      description: get user
      responses:
        "200":
          description: response 200
          content: 
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
    post:
      operationId: createUser
      description: create user
      requestBody: 
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "200":
          description: successfull create user
          content:
            application/json:
              schema:
                type: string
                example: success
    put:
      operationId: updateUsers
      description: update users
      requestBody: 
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/User"
      responses:
        "200":
          description: successfull create user
          content:
            application/json:
              schema:
                type: string
                example: success
      
                
components:
  schemas:
    User:
      type: object
      properties:
        id: 
          type: number
          example: 3
        username:
          type: string
          example: Oleksandt
servers:
  - description: main server
    url: example.com
    
      
          
